project:
  type: website

website:
  title: ""
  favicon: "favicon/favicon_white.png"
  navbar:
    logo: "favicon/favicon_gray24.png"
    logo_alt: 'An icon, a styleized monograph of the letter "K" inside an "M" (also the site favicon).'
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: education.qmd
        text: Education
      - href: projects.qmd
        text: Projects
  page-footer: 
    left: "made by me at some point"
    right: "[additional site information](siteinfo.qmd)"
        

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


